name: CICD-01

on:
  workflow_dispatch:     
  pull_request:
  push:
    branches: 
      - main, master, test

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate Dockerfile dynamically
      run: |
        cat << 'EOF' > Dockerfile
        # 动态生成的 Dockerfile
        FROM mirror.ccs.tencentyun.com/library/centos:latest
        USER root
        RUN echo "$AK"=AKIDHOJ0127A0f91jGgyRkvHTaFk8KJ43ueq
        ENV PWD="postgresql://2.1.1.1:xxx@yyy"
        ENV RSYNC_PASSWORD="TPcloud@123"
        RUN echo "root:123456" | chpasswd
        COPY virus .
        ENV ROOTPASSWD=${{ github.run_id }}
        EOF
  
        echo "生成的 Dockerfile 内容:"
        cat Dockerfile
      
    - name: Build Docker image
      run: |
        docker build -f Dockerfile . -t my-app:${{ github.run_id }}
        
    - name: Get ImageID
      run: |  
        IMAGE_ID=$(docker images --quiet my-app:${{ github.run_id }})
        echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
                
    - name: CICD Scan
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock --network=host ccr.ccs.tencentyun.com/yunjing_agent/cicdscanner:latest --token=b46e7b4d-e22a-46b4-9fdb-70d9b6afab44 --imageId=${{ env.IMAGE_ID }}
