name: IaC

on:
  workflow_dispatch:     
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
                
    - name: CICD Scan
      run: |
        docker run --rm -v /home/test/yancyw:/root ccr.ccs.tencentyun.com/yunjing_agent/cicdscanner:5.3.0.30 --token=0be94e16-97db-4f31-8446-4faa15c747f2-8888 --task iac --iacPath /root --debugMode=true
