name: IaC-Dockerfile

on:
  workflow_dispatch:     
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Generate Dockerfile dynamically
      run: |
        cat << 'EOF' > Dockerfile.${{ github.run_id }}
        FROM nginx
        RUN apt-get update
        COPY . /usr/share/nginx/html    
        EXPOSE 80
        EOF
  
        echo "生成的 Dockerfile 内容:"
        cat Dockerfile.${{ github.run_id }}
                
    - name: CICD Scan
      run: |
        docker run --rm -v /home/test:/home/test ccr.ccs.tencentyun.com/yunjing_agent/cicdscanner:latest --token=156699e1-8135-4346-b266-e7efd045a15f --task iac --iacPath /home/test/ --debugMode=true
