name: IaC-Dockerfile

on:
  workflow_dispatch:     
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Generate Dockerfile dynamically
      run: |
        cat << 'EOF' > Dockerfile.${{ github.run_id }}
        FROM nginx
        RUN apt-get update
        COPY . /usr/share/nginx/html    
        EXPOSE 80
        EOF
  
        echo "生成的 Dockerfile 内容:"
        cat Dockerfile.${{ github.run_id }}
                
    - name: CICD Scan
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/test/terraform:/home/test --network=host --pull always ccr.ccs.tencentyun.com/yunjing_agent/cicdscanner:latest --token=704f40eb-fe7c-4b1a-bde9-440732ed0eca --task iac --iacPath /home/test/variables.tf
