name: CICD-2

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
 
    steps:
      - name: login registry
        run: |
          docker login http://139.199.178.171:8089 --username "admin" --password "Harbor12345"

      - name: Build Docker image
        run: |
          python3 buildimage.py
