name: CICD-2

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
 
    steps:
      - name: Build Docker image
        run: |
          python3 buildimage.py
