name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Build Docker image
      run: |
        docker build -t my-app:${{ github.sha }} .
                
    - name: Push to registry
      run: |
        docker login http://139.199.178.171:8089 --username "admin" --password "Harbor12345"
        docker tag myapp:${{ github.sha }} 139.199.178.171:8089/cicd/cicd:${{ github.sha }}
        docker push 139.199.178.171:8089/cicd/cicd:${{ github.sha }}
